# This configuration file should be edited to fit the user's needs.

project: "rnaseq-tuxedo"

gtf: genes.gtf
genome: GRCh38
genome_index_base: genome

samples:
    path: path/to/samples 
    list: samples.csv
    paired_end: True
        forward: R1
        reverse: R2